### ISSUE TITLE
Feat: Split models and their logic in their own file

### ISSUE THREAD

**Issue by RedbeanGit** [bde-polytech-montpellier/bde-website-front#7]
A simple proposition. You can approve it or not ^^ 

# What's the problem?

Interfaces representing models, React component states, requests and responses are mixed. The project risks to lose quickly in maintainability.

# Suggested solutions

1. Review the file structure of the *models* folder and reorganize the interfaces

    a. *models* folder should **only store resource models** with one file per resource.
    b. **Functions** that apply to instances of these interfaces should be defined in the **same files of the concerned model**. Example: You will have one file named "goodie.ts" in "models" folder, containing "Goodie" interface and a "buyGoodie" function taking an instance of "Goodie".
    c. **Request** and **response** interfaces should be **moved in a *io* folder**
    d. **React component** interfaces should be **moved to the same file as the component** they are linked to, before the component render function. Most state interface (not every) should **have an associated *default*** constant in the same file that the component itself.

___

2. Rename interfaces and fields more explicitly by implementing naming conventions

    a. Each **model** simply has the **capitalized name of the resource** type it defines
    b. Each **request** (resp. **response**) should follow "<Action><Resource>Request" (resp. "<Action><Resource>Response"). Example: "CreateClubRequest"
    c. Each **React component state** should follow "<ComponentName>State"

**Comment by iusildra** [comment]
Ok for each except 2 of them :
- 1.b : the function is designed to work in a specific component, why should i augment it's visibility ?
- 2.a : i'm not sure to get what you mean

**Comment by RedbeanGit** [comment]
> 1.b : the function is designed to work in a specific component, why should i augment it's visibility ?

It only concerns utility functions that can be applied on a specific model. Example: If you have a **Team** model you may have a **findTeamUser(username: string)** function

 > 2.a : i'm not sure to get what you mean

It's just a suggestion about how to name model interfaces: "<ResourceType>" (no need to add a majuscule "i" at the beginning). You can accept or refuse this suggestion, you're the boss
